### PR TITLE
fix: handle few district seats

### LINKED ISSUE #122: fix: when the number of district seats is less than 4 they are no longer distributed correctly
As the number of district seats is lowered below 4, the sum of district seats is no longer the same as the number of district seats to distribute. 
S16AI7fxkF

### LINKED ISSUE #148: fix: assumption that all districts have a district seat
Currently, the code for calculating the most vulnerable seat assumes that all districts have at least one district seat. That is not always the case, such as when a user sets the number of district seats to a low number, such as 3.

### PR DESCRIPTION
**Pull request by Log234**
# Description
Fixes the bug that occurs when attempting to distribute very few district seats on the districts.
Also fixes a bug, where the calculation of most vulnerable seat assumes that all districts have a district seat and hence crashes when some districts have 0 district seats.

closes #122 
closes #148

### CODE REVIEW

**Comment by Log234** [comment]
Fixing some issues that seemed to crop up with the merge of new code.

**Comment by simendag** [comment]
@Log234 Did LGTM and the build check fail?

**Comment by Log234** [comment]
@simendag For some reason the list of branches/PRs are not loading in LGTM 
image

**Comment by Log234** [comment]
It seems as though there are some technical issues with the integrations or something:
image

**Comment by Log234** [comment]
LGTM has now approved the changes on lgtm.com, but the status has not been updated here.

**Pull request merged**
