### PR TITLE
fix: handle display of 0 leveling seats

### LINKED ISSUE #176: BUG: LevellingSeatsOverview year 1961 goes blank page
BUG_levellingSeatOverview1961
LevellingSeatOverview

The same "undefined" kind of error happened to ElectionOverView also.

### PR DESCRIPTION
**Pull request by Log234**
# Description
Correct the display of Levelingseat overview when there are 0 leveling seats.
Closes #176

### CODE REVIEW

**Comment by oysor** [comment]
> # Description
> 
> Correct the display of Levelingseat overview when there are 0 leveling seats.
> Closes #176


> # Description
> 
> Correct the display of Levelingseat overview when there are 0 leveling seats.
> Closes #176

**Comment by Log234** [comment]
> 
> 
> I still get the same error:
> TypeError: data[mostSeatsIndex] is undefined

I am not. Which settings are you using to produce the error?

**Comment by oysor** [comment]
> > I still get the same error:
> > TypeError: data[mostSeatsIndex] is undefined
> 
> I am not. Which settings are you using to produce the error?

Fireox
#error
Terminal: yarn start
#error

**Comment by Log234** [comment]
> 
> 
> > > I still get the same error:
> > > TypeError: data[mostSeatsIndex] is undefined
> > 
> > 
> > I am not. Which settings are you using to produce the error?
> 
> Fireox
> #error

Ensure you are in the right branch with the latest commit and open it in a private tab to ensure you are not accidentally using cached data.

**Comment by Log234** [comment]
wO3KLSa2UQ

**Comment by oysor** [comment]
It works! 

My bad. 

However, we could write an informative message instead of "Ingen data"
ingenData

**Comment by Log234** [comment]
> 
> 
> It works!
> 
> My bad.
> 
> However, we could write an informative message instead of "Ingen data"
> ingenData

Do you have a suggestion for a message? Ingen utjevningsmandater?

**Comment by oysor** [comment]
> > It works!
> > My bad.
> > However, we could write an informative message instead of "Ingen data"
> > ingenData
> 
> Do you have a suggestion for a message? Ingen utjevningsmandater?

"Utjevningsmandater fantes ikke før i tiden"

"Utjevningsmandater var ikke en del av valgordningen dette året"

"Utjevningsmandater er ikke med i dette årets valgordning"

"Valgordningen i 1961 hadde ikke utjevningsmandater"

**Comment by Log234** [comment]
> 
> 
> > > It works!
> > > My bad.
> > > However, we could write an informative message instead of "Ingen data"
> > > ingenData
> > 
> > 
> > Do you have a suggestion for a message? Ingen utjevningsmandater?
> 
> "Utjevningsmandater fantes ikke før i tiden"
> 
> "Utjevningsmandater var ikke en del av valgordningen dette året"
> 
> "Utjevningsmandater er ikke med i dette årets valgordning"
> 
> "Valgordningen i 1961 hadde ikke utjevningsmandater"

This will also be shown when the users sets utjevningsmandater to 0, so it isn't specifically tied to the year.

**Comment by oysor** [comment]
> > > > It works!
> > > > My bad.
> > > > However, we could write an informative message instead of "Ingen data"
> > > > ingenData
> > > 
> > > 
> > > Do you have a suggestion for a message? Ingen utjevningsmandater?
> > 
> > 
> > "Utjevningsmandater fantes ikke før i tiden"
> > "Utjevningsmandater var ikke en del av valgordningen dette året"
> > "Utjevningsmandater er ikke med i dette årets valgordning"
> > "Valgordningen i 1961 hadde ikke utjevningsmandater"
> 
> This will also be shown when the users sets utjevningsmandater to 0, so it isn't specifically tied to the year.

"Ingen utjevningsmandater"

Good enough for now.

**Comment by oysor** [comment]
> > > > > It works!
> > > > > My bad.
> > > > > However, we could write an informative message instead of "Ingen data"
> > > > > ingenData
> > > > 
> > > > 
> > > > Do you have a suggestion for a message? Ingen utjevningsmandater?
> > > 
> > > 
> > > "Utjevningsmandater fantes ikke før i tiden"
> > > "Utjevningsmandater var ikke en del av valgordningen dette året"
> > > "Utjevningsmandater er ikke med i dette årets valgordning"
> > > "Valgordningen i 1961 hadde ikke utjevningsmandater"
> > 
> > 
> > This will also be shown when the users sets utjevningsmandater to 0, so it isn't specifically tied to the year.
> 
> "Ingen utjevningsmandater"
> 
> Good enough for now.

"Valgordningen har ingen utjevningsmandater"

One size larger text maybe?

Good enough for me.

**Comment by Log234** [comment]
I am using the No data output of react-table, unsure how easy it would be to change font size, etc.

**Pull request merged**
